In [1]:
# Import libraries
import glob
import pandas as pd

In [2]:
path =r'/Users/cephra.stuart/Desktop/CitiBikeData' # use your path
allFiles = glob.glob(path + "/*.csv")

list_ = []

for file_ in allFiles:
    df = pd.read_csv(file_,index_col=None, header=0)
    list_.append(df)

frame = pd.concat(list_, axis = 0, ignore_index = True)

In [3]:
df = frame
df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,689,2018-12-01 00:00:04.3020,2018-12-01 00:11:33.8460,3359.0,E 68 St & Madison Ave,40.769157,-73.967035,164.0,E 47 St & 2 Ave,40.753231,-73.970325,35033,Subscriber,1989,1
1,204,2018-12-01 00:00:05.5330,2018-12-01 00:03:30.5230,3504.0,E 123 St & Lexington Ave,40.802926,-73.937900,3490.0,E 116 St & 2 Ave,40.796879,-73.937261,20501,Subscriber,1966,1
2,316,2018-12-01 00:00:10.2330,2018-12-01 00:05:27.2030,270.0,Adelphi St & Myrtle Ave,40.693083,-73.971789,243.0,Fulton St & Rockwell Pl,40.688226,-73.979382,18386,Subscriber,1984,1
3,726,2018-12-01 00:00:21.9570,2018-12-01 00:12:28.1830,495.0,W 47 St & 10 Ave,40.762699,-73.993012,3660.0,W 16 St & 8 Ave,40.741022,-74.001385,27616,Subscriber,1983,1
4,397,2018-12-01 00:00:29.6320,2018-12-01 00:07:07.4460,473.0,Rivington St & Chrystie St,40.721101,-73.991925,3467.0,W Broadway & Spring Street,40.724947,-74.001659,35096,Subscriber,1976,1

In [4]:
df['starttime'].max()

'2018-12-31 23:59:51.0850'

In [5]:
df['starttime'].min()

'2018-07-01 00:00:02.1120'

In [6]:
#Save dataframe to csv
df.to_csv("CitiBikeCombined.csv")

In [7]:
len(df)

9924203

In [8]:
dec = pd.read_csv("Dec18.csv",index_col=None, header=0)

In [9]:
dec.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,689,2018-12-01 00:00:04.3020,2018-12-01 00:11:33.8460,3359.0,E 68 St & Madison Ave,40.769157,-73.967035,164.0,E 47 St & 2 Ave,40.753231,-73.970325,35033,Subscriber,1989,1
1,204,2018-12-01 00:00:05.5330,2018-12-01 00:03:30.5230,3504.0,E 123 St & Lexington Ave,40.802926,-73.937900,3490.0,E 116 St & 2 Ave,40.796879,-73.937261,20501,Subscriber,1966,1
2,316,2018-12-01 00:00:10.2330,2018-12-01 00:05:27.2030,270.0,Adelphi St & Myrtle Ave,40.693083,-73.971789,243.0,Fulton St & Rockwell Pl,40.688226,-73.979382,18386,Subscriber,1984,1
3,726,2018-12-01 00:00:21.9570,2018-12-01 00:12:28.1830,495.0,W 47 St & 10 Ave,40.762699,-73.993012,3660.0,W 16 St & 8 Ave,40.741022,-74.001385,27616,Subscriber,1983,1
4,397,2018-12-01 00:00:29.6320,2018-12-01 00:07:07.4460,473.0,Rivington St & Chrystie St,40.721101,-73.991925,3467.0,W Broadway & Spring Street,40.724947,-74.001659,35096,Subscriber,1976,1

In [10]:
len(dec)

1016505

In [15]:
trips_df = df.groupby(['start station name','end station name']).size().reset_index(name = 'Number of Trips')

In [20]:
trips_df.sort_values(by='Number of Trips', ascending=False)

,start station name,end station name,Number of Trips
75429,Central Park S & 6 Ave,Central Park S & 6 Ave,4657
165929,Grand Army Plaza & Central Park S,Grand Army Plaza & Central Park S,3652
139199,E 7 St & Avenue A,Cooper Square & Astor Pl,3600
75359,Central Park S & 6 Ave,5 Ave & E 88 St,3511
233040,S 4 St & Wythe Ave,N 6 St & Bedford Ave,2985
210829,N 6 St & Bedford Ave,S 4 St & Wythe Ave,2796
264480,W 21 St & 6 Ave,9 Ave & W 22 St,2660
78798,Centre St & Chambers St,Centre St & Chambers St,2551
101704,E 10 St & Avenue A,Lafayette St & E 8 St,2550
299733,Yankee Ferry Terminal,Yankee Ferry Terminal,2369
220398,Pershing Square North,W 33 St & 7 Ave,2359
296646,West Thames St,South End Ave & Liberty St,2355
7682,12 Ave & W 40 St,West St & Chambers St,2321
219942,Pershing Square North,Broadway & W 32 St,2274
94516,DeKalb Ave & Vanderbilt Ave,DeKalb Ave & Hudson Ave,2262
220073,Pershing Square North,E 24 St & Park Ave S,2258
221561,Pier 40 - Hudson River Park,West St & Chambers St,2214
200767,McGuinness Blvd & Eagle St,Vernon Blvd & 50 Ave,2197
101957,E 102 St & 1 Ave,2 Ave & E 96 St,2176
260902,W 16 St & 8 Ave,W 20 St & 11 Ave,2170
165687,Grand Army Plaza & Central Park S,5 Ave & E 88 St,2134
265425,W 22 St & 10 Ave,W 22 St & 8 Ave,2121
195467,Little West St & 1 Pl,South End Ave & Liberty St,2111
236798,South End Ave & Liberty St,West Thames St,2105
268001,W 26 St & 8 Ave,W 27 St & 10 Ave,2100
260624,W 16 St & 8 Ave,E 16 St & 5 Ave,2058
295012,West Drive & Prospect Park West,West Drive & Prospect Park West,2042
232050,S 3 St & Bedford Ave,N 6 St & Bedford Ave,2029
227564,Richardson St & N Henry St,Graham Ave & Conselyea St,1997
7538,12 Ave & W 40 St,Pier 40 - Hudson River Park,1995
...,...,...,...
251390,Vernon Blvd & 50 Ave,1 Ave & E 110 St,1
251391,Vernon Blvd & 50 Ave,1 Ave & E 44 St,1
202406,Meserole Ave & Manhattan Ave,E 31 St & 3 Ave,1
202404,Meserole Ave & Manhattan Ave,E 25 St & 1 Ave,1
202402,Meserole Ave & Manhattan Ave,E 20 St & 2 Ave,1
202399,Meserole Ave & Manhattan Ave,E 2 St & Avenue A,1
79731,Centre St & Worth St,W 63 St & Broadway,1
147145,E 87 St & 3 Ave,W 56 St & 10 Ave,1
202393,Meserole Ave & Manhattan Ave,E 11 St & Broadway,1
251401,Vernon Blvd & 50 Ave,21 St & 36 Ave,1
157766,Frederick Douglass Blvd & W 129 St,Centre St & Chambers St,1
79729,Centre St & Worth St,W 56 St & 10 Ave,1
147144,E 87 St & 3 Ave,W 55 St & 6 Ave,1
202384,Meserole Ave & Manhattan Ave,Douglass St & 3 Ave,1
35032,7 St & 3 Ave,N 8 St & Driggs Ave,1
202381,Meserole Ave & Manhattan Ave,Division Ave & Hooper St,1
20855,31 St & Astoria Blvd,Banker St & Meserole Ave,1
202378,Meserole Ave & Manhattan Ave,Degraw St & Hoyt St,1
157771,Frederick Douglass Blvd & W 129 St,Cooper Square & Astor Pl,1
157772,Frederick Douglass Blvd & W 129 St,Dean St & 4 Ave,1
157773,Frederick Douglass Blvd & W 129 St,E 10 St & 5 Ave,1
251418,Vernon Blvd & 50 Ave,3 Ave & E 100 St,1
251420,Vernon Blvd & 50 Ave,3 Ave & E 71 St,1
251421,Vernon Blvd & 50 Ave,3 Ave & Schermerhorn St,1
79716,Centre St & Worth St,W 44 St & 5 Ave,1
147140,E 87 St & 3 Ave,W 47 St & 10 Ave,1
147139,E 87 St & 3 Ave,W 46 St & 11 Ave,1
202369,Meserole Ave & Manhattan Ave,Crescent St & 30 Ave,1
147138,E 87 St & 3 Ave,W 45 St & 6 Ave (OLD),1
165550,Graham Ave & Withers St,Rogers Ave & Sterling St,1